# Generated by Django 6.0.5 on 2026-05-12 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("niche", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="US", max_length=10)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("review_count", models.IntegerField(default=0)),
                ("gbp_status", models.CharField(blank=True, max_length=50)),
                ("has_website", models.BooleanField(default=False)),
                ("has_ssl", models.BooleanField(default=False)),
                ("pagespeed_score", models.IntegerField(blank=True, null=True)),
                ("has_meta_title", models.BooleanField(default=False)),
                ("has_meta_desc", models.BooleanField(default=False)),
                ("has_schema", models.BooleanField(default=False)),
                ("has_social", models.BooleanField(default=False)),
                ("opportunity_score", models.IntegerField(db_index=True, default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("saved", "Saved"),
                            ("contacted", "Contacted"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("audit_done", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-opportunity_score"],
                "indexes": [
                    models.Index(
                        fields=["niche", "city", "state", "country"],
                        name="leads_lead_niche_9b9154_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("niche", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="US", max_length=10)),
                ("total_results", models.IntegerField(default=0)),
                ("is_exhausted", models.BooleanField(default=False)),
                ("last_fetched", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["niche", "city", "state", "country"],
                        name="leads_searc_niche_b38b1e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SavedLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="leads.lead",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "lead")},
            },
        ),
    ]
