# Generated by Django 6.0.5 on 2026-05-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_searchcache_next_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="country",
            field=models.CharField(default="US", max_length=50),
        ),
        migrations.AlterField(
            model_name="searchcache",
            name="country",
            field=models.CharField(default="US", max_length=50),
        ),
    ]
