# Generated by Django 6.0.5 on 2026-05-21 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0003_alter_lead_country_alter_searchcache_country"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["niche", "city", "country"], name="leads_lead_niche_3dfd5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["city"], name="leads_lead_city_e501db_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["niche"], name="leads_lead_niche_c4b2a2_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["audit_done", "has_website", "email"],
                name="leads_lead_audit_d_068c4c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savedlead",
            index=models.Index(
                fields=["user", "lead"], name="leads_saved_user_id_965300_idx"
            ),
        ),
    ]
