# Generated by Django 6.0.5 on 2026-05-21 19:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0004_lead_leads_lead_niche_3dfd5d_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="savedlead",
            name="leads_saved_user_id_965300_idx",
        ),
    ]
