# Generated by Django 6.0.5 on 2026-07-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_remove_savedlead_leads_saved_user_id_965300_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='email_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='email_status',
            field=models.CharField(blank=True, default='unchecked', max_length=15),
        ),
    ]
