# Generated by Django 6.0.5 on 2026-05-08 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("free", "Free"), ("pro", "Pro"), ("max", "Max")],
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "price_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("stripe_price_id", models.CharField(blank=True, max_length=100)),
                ("search_limit", models.IntegerField(default=10)),
                ("backlink_search_limit", models.IntegerField(default=0)),
                ("ai_pitch_limit", models.IntegerField(default=5)),
                ("email_send_limit", models.IntegerField(default=20)),
                ("saved_leads_limit", models.IntegerField(default=10)),
                ("ai_chat_limit", models.IntegerField(default=0)),
                ("bulk_search_limit", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_invoice_id", models.CharField(max_length=100, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("currency", models.CharField(default="usd", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=10,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_customer_id", models.CharField(blank=True, max_length=100)),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("past_due", "Past Due"),
                            ("trialing", "Trialing"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.plan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("website_generation", "Website Generation"),
                            ("pdf_audit_reports", "PDF Audit Reports"),
                            ("ai_lead_scoring", "AI Lead Scoring"),
                            ("pipeline_crm", "Pipeline CRM"),
                            ("follow_up_sequences", "Follow-up Sequences"),
                            ("proposals_case_studies", "Proposals & Case Studies"),
                            ("competitor_comparison", "Competitor Comparison"),
                            ("niche_scanner", "Niche Scanner"),
                            ("csv_export_import", "CSV Export & Import"),
                            ("bulk_pitch_generation", "Bulk Pitch Generation"),
                            ("daily_email_automations", "Daily Email Automations"),
                            ("review_response_templates", "Review Response Templates"),
                            ("priority_support", "Priority Support"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="billing.plan",
                    ),
                ),
            ],
            options={
                "unique_together": {("plan", "feature")},
            },
        ),
        migrations.CreateModel(
            name="UsageCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("search", "Search"),
                            ("backlink_search", "Backlink Search"),
                            ("ai_pitch", "AI Pitch"),
                            ("email_send", "Email Send"),
                            ("ai_chat", "AI Chat"),
                            ("bulk_search", "Bulk Search"),
                        ],
                        max_length=20,
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                ("reset_date", models.DateField()),
                ("last_used", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "action", "reset_date"],
                        name="billing_usa_user_id_d1bf86_idx",
                    )
                ],
                "unique_together": {("user", "action", "reset_date")},
            },
        ),
    ]
