# Generated by Django 6.0.5 on 2026-05-08 22:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_event_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="usersubscription",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="plan",
            name="ai_pitch_limit",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="plan",
            name="email_send_limit",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="plan",
            name="saved_leads_limit",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="plan",
            name="search_limit",
            field=models.IntegerField(default=0),
        ),
    ]
