# Generated by Django 6.0.5 on 2026-05-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_stripewebhookevent_alter_usersubscription_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usagecounter",
            name="bonus",
            field=models.IntegerField(default=0),
        ),
    ]
