# Generated by Django 6.0.5 on 2026-05-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_usagecounter_bonus"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="team_seat_limit",
            field=models.IntegerField(default=1),
        ),
    ]
