# Generated by Django 6.0.5 on 2026-08-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_plan_team_seat_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('max', 'Max'), ('unlimited', 'Unlimited')], max_length=10, unique=True),
        ),
    ]
