# Generated by Django 6.0.5 on 2026-05-18 21:21

from django.db import migrations

def create_default_stages(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    PipelineStage = apps.get_model('pipeline', 'PipelineStage')
    
    stages_to_create = []
    
    for user in User.objects.all():
        if not PipelineStage.objects.filter(user=user).exists():
            stages_to_create.extend([
                PipelineStage(user=user, name="New", order=1, color="#E2E8F0"),
                PipelineStage(user=user, name="Contacted", order=2, color="#FEF08A"),
                PipelineStage(user=user, name="Interested", order=3, color="#93C5FD"),
                PipelineStage(user=user, name="Proposal Sent", order=4, color="#C4B5FD"),
                PipelineStage(user=user, name="Closed Won", system_key="closed_won", order=5, color="#86EFAC"),
                PipelineStage(user=user, name="Closed Lost", system_key="closed_lost", order=6, color="#FCA5A5"),
            ])
            
    if stages_to_create:
        PipelineStage.objects.bulk_create(stages_to_create)


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline", "0001_initial"),
        ("accounts", "0002_user_timezone"),
    ]

    operations = [
        migrations.RunPython(create_default_stages),
    ]
