# Generated by Django 6.0.5 on 2026-05-21 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0004_lead_leads_lead_niche_3dfd5d_idx_and_more"),
        ("pipeline", "0002_create_default_stages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pipelinelead",
            index=models.Index(
                fields=["user", "stage"], name="pipeline_pi_user_id_c753fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinelead",
            index=models.Index(
                fields=["user", "follow_up_date"], name="pipeline_pi_user_id_f4f55f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinestage",
            index=models.Index(
                fields=["user", "order"], name="pipeline_pi_user_id_43dfd3_idx"
            ),
        ),
    ]
