# Generated by Django 6.0.5 on 2026-05-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0004_lead_leads_lead_niche_3dfd5d_idx_and_more"),
        ("outreach", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outreachmessage",
            name="message_id",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name="campaignlead",
            index=models.Index(
                fields=["campaign", "status"], name="outreach_ca_campaig_e1c048_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignlead",
            index=models.Index(
                fields=["status", "next_step_date"],
                name="outreach_ca_status_3b04e2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outreachmessage",
            index=models.Index(
                fields=["campaign_lead"], name="outreach_ou_campaig_7e39ca_idx"
            ),
        ),
    ]
