# Generated by Django 6.0.5 on 2026-08-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0002_alter_outreachmessage_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='daily_send_limit',
            field=models.PositiveIntegerField(default=40),
        ),
    ]
