# Generated by Django 6.0.5 on 2026-08-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0003_emailaccount_daily_send_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlead',
            name='send_failures',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
