# Generated by Django 6.0.5 on 2026-07-31 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demosites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedsite',
            name='color_scheme',
            field=models.CharField(default='ai', max_length=20),
        ),
        migrations.AddField(
            model_name='generatedsite',
            name='custom_primary',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='generatedsite',
            name='custom_secondary',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='generatedsite',
            name='tone',
            field=models.CharField(default='auto', max_length=20),
        ),
        migrations.CreateModel(
            name='SiteInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='demosites.generatedsite')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
